apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jena-fuseki
  namespace: argocd
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/sync-wave: "-10"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: dkg-engine
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://glaciation-heu.github.io/jena-fuseki/helm-charts/
    chart: jena-fuseki
    targetRevision: 1.*.*
    helm:
      valuesObject:
        ingressHostName: jena-fuseki.integration
  syncPolicy:
    automated:
     prune: true
     selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
