apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: data-storage-service-db
  namespace: argocd
spec:
  source:
    helm: 
      valuesObject: 
        ingressHostName: dss-db.uc2
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: metadata-service
  namespace: argocd
spec:
  source:
    helm: 
      valuesObject: 
        ingressHostName: metadata.uc2
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: data-storage-service
  namespace: argocd
spec:
  source:
    helm: 
      valuesObject: 
        ingressHostName: data-storage.uc2
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kg-exporter
  namespace: argocd
spec:
  source:
    helm: 
      valuesObject: 
        ingressHostName: kg-exporter.uc2
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prediction-service
  namespace: argocd
spec:
  source:
    helm: 
      valuesObject: 
        ingressHostName: prediction.uc2
